# Slide di Presenta in aula · Capitolo 1 · La comunicazione digitale
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from slidelib import *
configura(modulo='Reti e Internet')
c = Capitolo(1)
OUT = sys.argv[1] if len(sys.argv) > 1 else os.path.join(QUI, '..')

S = [
 c.COP('Chi parla, chi ascolta, attraverso che cosa e con quali regole.'),
 c.DOM(0),
 # 1.1
 c.SEZ('1.1', 'Sei elementi, sempre gli stessi'),
 {'tipo': 'tessere', 'titolo': 'Comunicare = trasferire un’informazione', 'tessere': [
   ['user', 'Mittente', 'chi invia · tu che scrivi'], ['user', 'Destinatario', 'chi riceve · il tuo amico'], ['message-square', 'Messaggio', '“Ci vediamo alle 5?”'],
   ['binary', 'Codice', 'le regole: l’italiano, poi i bit'], ['radio', 'Canale', 'onde radio, cavi, fibra'], ['zap', 'Rumore', 'segnale debole, interferenze']]},
 c.SC('F1.1.1', 'Lo schema della comunicazione'),
 {'tipo': 'punti', 'titolo': 'Codice e rumore', 'punti': [
   ['binary', 'Mittente e destinatario devono usare **lo stesso codice**'], ['message-circle-question', 'Scrivo in giapponese a chi non lo conosce → arriva, ma **non si capisce**'],
   ['network', 'Nelle reti l’accordo sul codice e sulle regole = **protocollo**'], ['zap', 'Il rumore c’è sempre: una buona comunicazione **lo tollera**']]},
 c.ERR(0),
 # 1.2
 c.SEZ('1.2', 'Banda, throughput, latenza, jitter'),
 c.DOM(1),
 {'tipo': 'punti', 'titolo': 'La larghezza di banda (*bandwidth*)', 'punti': [
   ['gauge', 'Quantità **massima** di dati che un canale trasporta **in un secondo**'], ['binary', 'Si misura in **bit al secondo**: kbps · Mbps · Gbps · Tbps'],
   ['zap', 'Il segnale viaggia **sempre alla stessa velocità** (≈ 200.000 km/s nel rame e nella fibra)'], ['layers', 'Una connessione “più veloce” mette **più bit al secondo** sul canale']],
  'nota': 'La banda è la **larghezza del tubo**, non la velocità dell’acqua'},
 {'tipo': 'tabella', 'titolo': 'Le unità della banda', 'righe': [['Unità', 'Simbolo', 'Valore'], ['kilobit al secondo', 'kbps', '1.000 bit/s'], ['megabit al secondo', 'Mbps', '1.000.000 bit/s'], ['gigabit al secondo', 'Gbps', '1.000.000.000 bit/s'], ['terabit al secondo', 'Tbps', '1.000.000.000.000 bit/s']]},
 {'tipo': 'formula', 'titolo': 'Bit e byte: l’errore più comune', 'formula': 'MB al secondo = Mbps ÷ 8', 'righe': [
   ['connessioni', 'bit al secondo · **Mbps** (b minuscola)'], ['file', 'byte · **MB** (B maiuscola)'], ['100 Mbps', 'al massimo **12,5 MB** al secondo']]},
 c.ERR(1),
 {'tipo': 'formula', 'titolo': 'Esempio: un videogioco da 50 GB a 100 Mbps', 'formula': '50 GB = 400.000 megabit', 'righe': [['400.000 ÷ 100', '**4.000 secondi**'], ['4.000 s', '≈ **1 ora e 7 minuti** (caso ideale)']]},
 c.WG('download', 'Prova tu: quanto ci metto a scaricare?'),
 c.DOM(2),
 {'tipo': 'confronto', 'titolo': 'Download e upload', 'a': {'icona': 'download', 'titolo': 'Download', 'tono': 'buono', 'righe': ['• dati **ricevuti**', '• guardare un video, scaricare un file', '+ di solito la banda **più alta**']},
  'b': {'icona': 'upload', 'titolo': 'Upload', 'righe': ['• dati **inviati**', '• caricare un video, videochiamare', '- spesso **più bassa**']},
  'verdetto': 'Quasi tutti ricevono più di quanto inviano → l’operatore dà di più al download: la **A** di ADSL = *Asymmetric*. In FTTH spesso è **simmetrica**'},
 c.DOM(3),
 {'tipo': 'punti', 'titolo': 'Throughput: la velocità effettiva', 'punti': [
   ['activity', 'I dati che passano **davvero** in un secondo: quasi sempre **meno** della banda'], ['users', 'Linea **condivisa** con altri utenti e dispositivi'],
   ['wifi', 'Il **Wi-Fi** perde velocità con muri e interferenze'], ['server', 'Il server può essere **lento o lontano**'], ['mail', 'Parte dei bit è **informazione di servizio** (busta e francobollo)']]},
 {'tipo': 'punti', 'titolo': 'Esempio: “1 Gbps” misurato in camera', 'punti': [['smartphone', 'Telefono in camera, lontano dal router → **300 Mbps**'], ['wifi', 'Il **collo di bottiglia** è il Wi-Fi'], ['cable', 'Via cavo il test si avvicina molto al valore dichiarato']]},
 {'tipo': 'punti', 'titolo': 'La latenza (*ping*)', 'punti': [
   ['timer', 'Tempo da quando un dato **parte** a quando **arriva** · in **millisecondi**'], ['map', '**Distanza**: Milano → New York ≈ 33 ms · satellite geostazionario > 240 ms'],
   ['router', '**Router attraversati**: ognuno legge e decide'], ['list', '**Code**: router congestionato → il pacchetto aspetta']],
  'nota': 'Banda = quanto il tubo è **largo** · latenza = quanto è **lungo**'},
 c.AN('F1.2.2', 'Due tubi: banda e latenza'),
 {'tipo': 'confronto', 'titolo': 'Che cosa conta di più?', 'a': {'icona': 'video', 'titolo': 'Streaming di un film', 'righe': ['• conta la **banda**', '• qualche secondo di ritardo non si nota']},
  'b': {'icona': 'gamepad-2', 'titolo': 'Gioco online, videochiamata', 'tono': 'buono', 'righe': ['• conta la **latenza**', '• attività **interattive**']}},
 {'tipo': 'punti', 'titolo': 'Il jitter', 'punti': [['activity', 'Quanto la latenza **varia** da un pacchetto all’altro'], ['route', 'I pacchetti non fanno tutti lo stesso viaggio: code, strade diverse'],
   ['video', 'Arrivano a **intervalli irregolari** → l’immagine va **a scatti**']]},
 c.AN('F1.2.3', 'Il jitter'),
 {'tipo': 'punti', 'titolo': 'In laboratorio: lo speed test', 'punti': [['gauge', 'speedtest.net o fast.com: Wi-Fi della scuola, rete di casa, rete del telefono'],
   ['list', 'Annotare **download, upload e ping** in un **Foglio Google condiviso**'], ['activity', 'Grafico a barre: più banda e meno latenza coincidono?']], 'foto': c.FO('F1.2.4')},
 c.ERR(2),
 # 1.3
 c.SEZ('1.3', 'Su che cosa viaggiano i bit'),
 c.DOM(4),
 {'tipo': 'confronto', 'titolo': 'Due famiglie di mezzi trasmissivi', 'a': {'icona': 'cable', 'titolo': 'Guidati (cablati)', 'tono': 'buono', 'righe': ['• il segnale viaggia **in un cavo**', '• rame (doppino, coassiale) e fibra', '+ **veloci, stabili, sicuri**']},
  'b': {'icona': 'wifi', 'titolo': 'Non guidati (*wireless*)', 'righe': ['• onda elettromagnetica **nell’aria**', '• Wi-Fi, Bluetooth, cellulare, satelliti', '+ **comodi**, ci si muove', '- distanza, ostacoli, interferenze']}},
 c.SC('F1.3.1', 'La mappa dei mezzi'),
 {'tipo': 'punti', 'titolo': 'Il doppino (*twisted pair*)', 'punti': [['cable', '**Coppie di fili di rame intrecciati**'], ['network', 'Cavo **Ethernet**: 4 coppie, connettore **RJ45**'],
   ['zap', 'L’intreccio **cancella i disturbi**: il ricevitore misura la **differenza** tra i due fili']], 'foto': c.FO('F1.3.2')},
 c.AN('F1.3.3', 'Perché i fili sono intrecciati'),
 {'tipo': 'punti', 'titolo': 'Dal modem all’ADSL', 'punti': [['layers', 'Categorie Cat 5e, 6, 6a…: intreccio più curato → **da 1 a 10 Gbps**'],
   ['volume-2', 'Anni ’90: modem sulla linea telefonica, bit come **suoni**, max **56 kbps**, telefono occupato'], ['signal', '**ADSL**: stesso doppino, **frequenze più alte** → telefono e Internet insieme, fino a ~20 Mbps']],
  'foto': c.FO('F1.3.4')},
 {'tipo': 'punti', 'titolo': 'Il cavo coassiale', 'punti': [['cable', 'Filo centrale + isolante + **calza metallica** + guaina'], ['shield', 'La **calza fa da scudo** ai disturbi'], ['tv', 'Antenna della **TV**, in alcuni paesi Internet via cavo']], 'foto': c.FO('F1.3.5', 'Gli strati del coassiale')},
 {'tipo': 'punti', 'titolo': 'La fibra ottica', 'punti': [['sparkles', 'Filo di **vetro** sottile come un capello'], ['binary', 'Impulsi di **luce**: accesa = 1, spenta = 0'],
   ['layers', '**Nucleo** + **mantello**'], ['repeat', '**Riflessione totale**: la luce rimbalza e resta dentro · niente pieghe a gomito']], 'foto': c.FO('F1.3.6')},
 c.AN('F1.3.7', 'La luce intrappolata'),
 {'tipo': 'tessere', 'titolo': 'Perché la fibra vince', 'tessere': [['gauge', 'Banda enorme', 'luce accesa e spenta miliardi di volte · più colori insieme'], ['map', 'Distanze lunghe', 'il vetro assorbe pochissima luce'],
   ['zap', 'Niente disturbi', 'luce, non corrente elettrica'], ['lock', 'Sicurezza', 'la luce non trapela']], 'nota': 'Svantaggi: **delicata**, difficile da giuntare · il costo vero è **lo scavo**'},
 {'tipo': 'confronto', 'titolo': '“Fibra” può voler dire due cose', 'a': {'icona': 'cable', 'titolo': 'FTTC · *Fiber To The Cabinet*', 'righe': ['• fibra fino all’**armadio in strada**', '- ultimo tratto **in rame**', '- max ~200 Mbps, **cala con la distanza**']},
  'b': {'icona': 'sparkles', 'titolo': 'FTTH · *Fiber To The Home*', 'tono': 'buono', 'righe': ['• fibra **fino all’appartamento**', '+ **1–10 Gbps**', '+ la distanza non conta']}},
 {'tipo': 'foto', 'titolo': 'L’armadio di strada', 'foto': [c.FO('F4.3.2', 'In FTTC qui arriva la fibra e parte il rame')]},
 c.AN('F4.3.3', 'FTTC e FTTH'),
 c.WG('distanza', 'Prova tu: quanto sei lontano dall’armadio?'),
 c.DOM(5),
 {'tipo': 'punti', 'titolo': 'Onde elettromagnetiche e frequenza', 'punti': [['waves', 'Frequenza **bassa** → arriva lontano, aggira gli ostacoli'], ['gauge', 'Frequenza **alta** → più dati, ma la fermano muri, pioggia, foglie'],
   ['radio', '**Onde radio**: FM, TV, cellulare, Wi-Fi, Bluetooth'], ['satellite-dish', '**Microonde**: ponti radio, satelliti, 5G alto · antenne **a vista**'], ['eye', '**Infrarossi**: telecomando · stessa stanza']]},
 c.SC('F1.3.11', 'Lo spettro'),
 {'tipo': 'punti', 'titolo': 'L’aria è di tutti', 'punti': [['users', 'Stessa frequenza nello stesso posto → **ci si disturba**'], ['building-2', 'Frequenze = **risorsa pubblica divisa per legge**'],
   ['key', 'Bande in esclusiva: le **aste del 5G**, pagate miliardi'], ['wifi', 'Bande libere a bassa potenza: **2,4 e 5 GHz**']],
  'nota': 'Il telecomando non passa attraverso una persona; la chiamata arriva anche in tasca'},
 {'tipo': 'confronto', 'titolo': 'Il Wi-Fi: due bande', 'a': {'icona': 'wifi', 'titolo': '2,4 GHz', 'righe': ['+ arriva **più lontano**', '+ attraversa meglio i muri', '- **più lento e affollato**']},
  'b': {'icona': 'wifi', 'titolo': '5 GHz (e 6 GHz)', 'tono': 'buono', 'righe': ['+ **più veloce**, canali più larghi', '- **portata minore**', '- i muri lo fermano di più']},
  'verdetto': 'In camera il 5 GHz “prende male” ma il 2,4 sì? **Non è un guasto**'},
 c.SC('F2.8.1', '2,4 e 5 GHz nella stessa casa'),
 {'tipo': 'punti', 'titolo': 'Wi-Fi e Bluetooth', 'punti': [['wifi', 'Wi-Fi: rete locale senza cavi tramite un **access point** · decine di metri'], ['layers', 'Dal Wi-Fi 4 al **Wi-Fi 7**: più velocità e **più dispositivi insieme**'],
   ['bluetooth', 'Bluetooth: dispositivi **vicinissimi**, **poca potenza** → poca batteria, pochi dati']], 'foto': c.FO('F2.8.3')},
 {'tipo': 'storia', 'titolo': 'Un re vichingo nel tuo telefono', 'anno': 'X secolo', 'foto': c.FOBOX('1.3', 'Le rune H e B'), 'punti': [
   ['crown', '**Harald “Dente Blu” Gormsson** unificò Danimarca e Norvegia'], ['bluetooth', 'Il Bluetooth doveva **unire** dispositivi diversi'], ['sparkles', 'Il logo unisce le rune delle iniziali **H** e **B**']]},
 c.DOM(6),
 {'tipo': 'punti', 'titolo': 'RFID', 'punti': [['tag', 'Identifica un oggetto **a distanza** con un’etichetta radio, il **tag**'], ['cpu', 'Chip + antenna · **niente batteria**: l’energia arriva dall’onda del lettore'],
   ['shopping-bag', 'Antitaccheggio, badge, biglietti, passaporti, Telepass']], 'foto': c.FO('F2.8.4')},
 {'tipo': 'punti', 'titolo': 'NFC', 'punti': [['smartphone', 'Derivato dall’RFID, funziona a **pochi centimetri**'], ['shield', 'La distanza ridotta **è una protezione**'],
   ['credit-card', 'Pagamenti contactless, abbinare le cuffie, carta d’identità elettronica']], 'foto': c.FO('F2.8.5')},
 c.ERR(3),
 {'tipo': 'confronto', 'titolo': 'Satelliti per telecomunicazioni', 'a': {'icona': 'satellite', 'titolo': 'Geostazionari · 36.000 km', 'righe': ['+ sembrano **fermi**: antenna sempre puntata', '+ ne bastano pochi', '- ≈ 144.000 km di viaggio → **oltre mezzo secondo**']},
  'b': {'icona': 'satellite', 'titolo': 'Orbita bassa (LEO) · 550 km', 'tono': 'buono', 'righe': ['+ latenza **bassa**: decine di ms', '- si muovono: **ne servono migliaia**', '• costellazioni come **Starlink**']},
  'verdetto': 'Indispensabili dove i cavi non arrivano: navi, aerei, montagne, disastri'},
 c.AN('F4.3.5', 'Geostazionari e orbita bassa'),
 {'tipo': 'foto', 'titolo': 'Un’antenna Starlink', 'foto': [c.FO('F4.3.6', 'Punta il cielo e segue i satelliti che passano')]},
 c.DOM(7),
 {'tipo': 'tabella', 'titolo': 'Il confronto (valori indicativi)', 'righe': [['Tecnologia', 'Ultimo tratto', 'Download', 'Latenza'], ['Linea commutata (’90)', 'doppino, come voce', '56 kbps', 'alta'], ['ADSL', 'doppino, frequenze alte', 'fino a 20 Mbps', '20–40 ms'],
   ['FTTC (VDSL)', 'fibra + doppino', '30–200 Mbps', '10–20 ms'], ['FTTH', 'fibra fino in casa', '1–10 Gbps', '5–10 ms'], ['Satellite LEO', 'onde radio', '100–250 Mbps', '25–60 ms'],
   ['Satellite geostazionario', 'onde radio, 36.000 km', 'decine di Mbps', '600 ms e oltre'], ['4G / 5G', 'onde radio dalla cella', 'decine–centinaia Mbps / oltre 1 Gbps', '30–50 / 10–20 ms']]},
 c.AN('F1.2.1', 'La gara dei download'),
 {'tipo': 'punti', 'titolo': 'Cavo e onda radio convivono', 'punti': [['cable', 'Il **cavo** vince per velocità, stabilità e sicurezza'], ['wifi', 'L’**onda radio** vince per comodità e mobilità'], ['building-2', 'La fibra porta i dati all’edificio, il Wi-Fi li distribuisce nelle stanze']]},
 c.ERR(4),
 # 1.4
 c.SEZ('1.4', 'Chi trasmette, in che direzione, quando'),
 {'tipo': 'tessere', 'titolo': 'Tre modi di usare un canale', 'tessere': [['move-right', 'Simplex', 'una sola direzione · radio FM, TV, sensore'], ['arrow-left-right', 'Half-duplex', 'due direzioni **a turno** · walkie-talkie, hub'], ['repeat', 'Full-duplex', 'due direzioni **insieme** · telefonata, switch']]},
 c.AN('F1.4.1', 'Simplex, half-duplex, full-duplex'),
 c.DOM(8),
 {'tipo': 'confronto', 'titolo': 'Sincrona o asincrona?', 'a': {'icona': 'clock', 'titolo': 'Sincrona', 'righe': ['• presenti **nello stesso momento**', '• telefonata, videochiamata', '• lezione in diretta su Meet']},
  'b': {'icona': 'mail', 'titolo': 'Asincrona', 'tono': 'buono', 'righe': ['• il messaggio **si legge più tardi**', '• email, compito su Classroom, commento a un post', '• WhatsApp: asincrono, usato quasi in diretta']},
  'verdetto': 'Asincrono = qualcuno **conserva** il messaggio nel frattempo'},
 c.ERR(5),
 c.DOM(9),
 # 1.5
 c.SEZ('1.5', 'Come condividere gli stessi cavi'),
 {'tipo': 'punti', 'titolo': 'Commutazione di circuito', 'punti': [['link', 'Prima di parlare si costruisce un **collegamento riservato**'], ['lock', 'Resta tuo **per tutta la conversazione**, anche nei silenzi'],
   ['phone', 'Così funzionava la **rete telefonica tradizionale**'], ['circle-check', '**Qualità garantita**'], ['circle-x', '**Spreco**: nessun altro può usarlo · se un tratto si guasta, cade']], 'foto': c.FO('F1.5.1')},
 {'tipo': 'punti', 'titolo': 'Commutazione di pacchetto', 'punti': [['package', 'Dati divisi in **pacchetti**, ognuno con l’indirizzo'], ['route', 'Ognuno **viaggia per conto suo**: cavi condivisi istante per istante'],
   ['list', 'In coda nei nodi · all’arrivo **rimessi in ordine**'], ['circle-check', '**Efficienza** e **robustezza** ai guasti'], ['circle-x', '**Tempi non garantiti**: latenza variabile, jitter']]},
 c.AN('F1.5.2', 'Circuito o pacchetti?'),
 {'tipo': 'confronto', 'titolo': 'Esempio: pullman o autobus di linea?', 'a': {'icona': 'bus', 'titolo': 'Pullman noleggiato', 'righe': ['• posti **riservati** alla classe', '- metà possono restare **vuoti**'], 'piede': 'circuito'},
  'b': {'icona': 'bus', 'titolo': 'Autobus di linea', 'tono': 'buono', 'righe': ['• mezzi **condivisi** con altri', '+ nessun posto inutilizzato', '• si arriva in momenti diversi'], 'piede': 'pacchetti'},
  'verdetto': 'Limite: un pacchetto può **perdersi** e va richiesto di nuovo (paragrafo 3.6)'},
 {'tipo': 'storia', 'titolo': 'Due inventori, un’idea', 'anno': 'anni ’60', 'icona': 'history', 'punti': [
   ['shield', 'USA · **Paul Baran**: una rete che **sopravviva a un attacco nucleare**'], ['network', 'Inghilterra · **Donald Davies**: condividere i costosi collegamenti, nome **pacchetti**'], ['globe', 'Le idee confluiscono in **ARPANET**']]},
 {'tipo': 'punti', 'titolo': 'Oggi anche la voce viaggia a pacchetti', 'punti': [['phone', 'Chiamate WhatsApp e videochiamate'], ['signal', 'VoLTE del 4G e telefonia fissa VoIP']]},
 c.DOM(10),
]
c.scrivi(OUT, S)
